development:
  adapter: postgresql
  encoding: unicode
  database: myapp
  pool: 5
  username: postgres
  password: 123
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: postgres
  password: 123
  host: localhost